#!/bin/bash

#### Sccript de instalação do MATE no Debian Wheezy ####

echo "Limpando a Sources.list da linha 1 a linha 20"

sed -i '1,20d' /etc/apt/sources.list | more

su -c "echo '#### Repósitório Debian Wheezy ####' >> /etc/apt/sources.list"
su -c "echo 'deb http://http.debian.net/debian/ wheezy main contrib non-free' >> /etc/apt/sources.list"
su -c "echo 'deb http://sft.if.usp.br/debian-security/ wheezy/updates main contrib non-free' >> /etc/apt/sources.list"
su -c "echo 'deb http://http.debian.net/debian/ wheezy-updates main contrib non-free' >> /etc/apt/sources.list"
su -c "echo 'deb http://http.debian.net/debian/ wheezy-backports main contrib non-free' >> /etc/apt/sources.list"

#### Repositório MATE para Debian Wheezy ####

su -c "echo '# main repository' >> /etc/apt/sources.list.d/mate-desktop.list"
su -c "echo 'deb http://repo.mate-desktop.org/debian wheezy main' >> /etc/apt/sources.list.d/mate-desktop.list"
su -c "echo '#' >> /etc/apt/sources.list.d/mate-desktop.list"
su -c "echo '# mirrors' >> /etc/apt/sources.list.d/mate-desktop.list"
su -c "echo 'deb http://packages.mate-desktop.org/repo/debian wheezy main' >> /etc/apt/sources.list.d/mate-desktop.list"
su -c "echo 'deb http://mirror1.mate-desktop.org/debian wheezy main' >> /etc/apt/sources.list.d/mate-desktop.list"

echo "Atualização da lista de repositórios"

apt-get update

apt-get --yes --quiet --allow-unauthenticated install mate-archive-keyring -y --force-yes

apt-get update

#### Instalação dos diretórios do usuário: Documentos, Downloads, Música, Imagens, Vídeos, etc.

apt-get install xdg-user-dirs -y --force-yes

#### Instalação do Xorg

apt-get install xorg -y --force-yes

#### Instalação de MATE

apt-get install mate-desktop-environment-extra -y --force-yes

#### Instalação e configuração de lightdm

apt-get install lightdm -y --force-yes

dpkg-reconfigure lightdm

#### Instalação do navegador Iceweasel

apt-get install iceweasel -y --force-yes

#### Remoção do Script

rm mate-netinst.sh

#### Reiniciando o sistema

shutdown -r now
